language: node_js
node_js:
  - "0.10"
env:
  - NODE_ENV=travis
services:
  - mongodb

before_script:
  - sudo apt-get -y update 

script: exit 0

after_script:
  - sudo apt-get install -y sshpass
  - sshpass -p "nandoscats" hackpartners@hacka.party 'cd /home/hackpartners/web/hacka.party/private/hacka.party && git clone'
